/*
 * File: app/store/ConfigStore.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.store.ConfigStore', {
    extend: 'Ext.data.Store',
    requires: [
        'Painometer.model.Config'
    ],

    config: {
        model: 'Painometer.model.Config',
        storeId: 'configStoreId',
        proxy: {
            type: 'localstorage',
            id: 'configStoreProxy'
        },
        listeners: [
            {
                fn: 'onStoreLoad',
                event: 'load'
            }
        ]
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {
        alert("load store");
    }

});