/*
 * File: app/view/CASPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.view.CASPanel', {
    extend: 'Ext.Container',
    alias: 'widget.caspanel',
    requires: [
        'Painometer.view.InfoContainer'
    ],

    config: {
        style: 'background-color:white;',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'container',
                id: 'CASSliderCont',
                style: 'background-color:white;',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'sliderfield',
                        centered: true,
                        cls: 'sencha-cas-slider',
                        id: 'CASSlider'
                    },
                    {
                        xtype: 'InfoContainer',
                        bottom: '0px',
                        docked: 'bottom',
                        height: '25px',
                        itemId: 'infoCAS',
                        right: '0px',
                        tpl: [
                            '<div class="x-inner x-layout-hbox" id="ext-element-1053" style="-webkit-box-align: end; -webkit-box-pack: end; "><div class="x-button x-iconalign-center x-button-info_btn-small" id="canvas-ExtBox1-ext-gen14191" style="border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; width: 22px !important; "><span style="display: none; " class="x-badge"></span><span class="x-button-icon info x-icon-mask" style="" id="ext-element-1054"></span><span style="display: none; " class="x-button-label"></span></div></div>'
                        ],
                        width: '25px',
                        layout: {
                            type: 'fit'
                        }
                    }
                ]
            }
        ]
    }

});