/*
 * File: app/view/ConfigPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.view.ConfigPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.configpanel',

    config: {
        id: 'ConfigPanel',
        ui: '',
        layout: {
            align: 'center',
            type: 'vbox'
        },
        scrollable: {
            direction: 'vertical'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Painometer',
                items: [
                    {
                        xtype: 'button',
                        id: 'okConfig',
                        ui: 'confirm',
                        text: 'OK'
                    },
                    {
                        xtype: 'button',
                        id: 'creditsbtn',
                        ui: 'forward',
                        iconAlign: 'right',
                        text: 'Crèdits',
                        align: 'right'
                    }
                ]
            },
            {
                xtype: 'container',
                data: {
                    value: 10
                },
                height: 210,
                id: 'ValueCont',
                style: 'text-align: center; font-size: 135px; margin: 15px; border: 15px; border-style: groove; padding: 0px; padding-top: 5px;',
                tpl: [
                    '{value}'
                ],
                width: 260
            },
            {
                xtype: 'fieldset',
                width: '100%',
                layout: {
                    type: 'default'
                },
                items: [
                    {
                        xtype: 'selectfield',
                        height: '',
                        id: 'ScaleSel',
                        itemId: 'ScaleSel',
                        label: 'Escala',
                        labelAlign: 'bottom',
                        labelWidth: '49.5%',
                        name: 'escalaType',
                        displayField: 'label',
                        store: 'scaleTypesStoreId',
                        valueField: 'idScale'
                    },
                    {
                        xtype: 'togglefield',
                        id: 'reset',
                        itemId: 'reset',
                        label: 'Reset',
                        labelWidth: '45%'
                    },
                    {
                        xtype: 'selectfield',
                        height: '',
                        hidden: true,
                        width: '',
                        label: 'Idioma',
                        labelAlign: 'bottom',
                        labelWidth: '40%',
                        name: 'Language',
                        displayField: 'label',
                        store: 'languageStoreId',
                        valueField: 'idLang\n'
                    }
                ]
            }
        ]
    }

});