/*
 * File: app/view/ConfigCard.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.view.ConfigCard', {
    extend: 'Ext.Container',
    alias: 'widget.configCard',
    requires: [
        'Painometer.view.ConfigPanel',
        'Painometer.view.CreditsContainer'
    ],

    config: {
    	id: "configCard",
        layout: {
            animation: 'slide',
            type: 'card'
        },
        items: [
            {
                xtype: 'configpanel',
                id: 'configPanel'
            },
            {
                xtype: 'creditscontainer',
                id: 'Creditscontainer'
            }
        ]
    }

});