/*
 * File: app/view/InfoContainer.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.view.InfoContainer', {
    extend: 'Ext.Container',
    alias: 'widget.InfoContainer',

    config: {
        bottom: '0px',
        docked: 'right',
        height: '35px',
        id: 'infoContainerID',
        right: '0px',
        style: '',
        width: '35px',
        zIndex : 4,
        items: [
            {
                xtype: 'button',
                height: '30px',
                id: 'infoBtn',
                style: 'border:0;',
                ui: 'info_btn-small',
                width: '30px',
                iconCls: 'info',
                iconMask: true
            }
        ]
    }

});