/*
 * File: app/view/VASPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.view.VASPanel', {
    extend: 'Ext.Container',
    alias: 'widget.VASPanel',
    requires: [
        'Painometer.view.InfoContainer'
    ],
	zIndex : 0,
    config: {
        id: 'VASPanel',
        style: 'background-color:white;',
        layout: {
            type: 'fit'
        },
        zIndex : 0,
        items: [
            {
                xtype: 'container',
                id: 'VASSliderCont',
                style: 'background-color:white;',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'sliderfield',
                        centered: true,
                        cls: 'sencha-vas-slider',
                        id: 'VASSlider'
                    }
                ]
            },
            {
                xtype: 'InfoContainer',
                id: 'VASInfoCont'
            }
        ]
    }

});