/*
 * File: app/model/Config.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.model.Config', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
            {
                name: 'scale',
                type: 'int',
                defaultValue: 0
            },
            {
                name: 'language',
                type: 'int',
                defaultValue: 0
            },
            {
                name: 'value',
                type: 'int',
                defaultValue: 0
            },
            {
            	name: 'reset',
            	type: 'boolean',
            	defaultValue: true
            },
            {
            	name: 'viewIndex',  // the index of the view in the mainContainer
            	type: 'int',
            	defaultValue: 0	
            }
        ],
        proxy: {
            type: 'localstorage',
            id: 'painometerProxy'
        }
    }
});