/*
 * File: app/view/ui/ConfigPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.view.ui.ConfigPanel', {
    extend: 'Ext.form.Panel',

    config: {
        id: 'ConfigPanel',
        layout: {
            type: 'vbox'
        },
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Painometer',
                items: [
                    {
                        xtype: 'button',
                        id: 'okConfig',
                        ui: 'confirm',
                        text: 'OK'
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 183,
                id: 'ValueCont',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'dataview',
                        centered: true,
                        height: 130,
                        id: 'Value',
                        style: 'border-width:0.1 px; border-style:solid;',
                        width: 130,
                        scrollable: false,
                        itemTpl: [
                            '<div style=" padding-top:-15px;',
                            'font-size:100px;"><center>{value}</center></div>'
                        ],
                        store: 'configStoreId'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                layout: {
                    type: 'default'
                },
                instructions: 'Opcions generals de l\'eina',
                title: 'Opcions',
                items: [
                    {
                        xtype: 'selectfield',
                        height: '',
                        id: 'ScaleSel',
                        itemId: 'ScaleSel',
                        width: '',
                        label: 'Escala',
                        labelAlign: 'bottom',
                        labelWidth: '40%',
                        name: 'escalaType',
                        displayField: 'label',
                        store: 'scaleTypesStoreId',
                        valueField: 'idScale'
                    },
                    {
                        xtype: 'selectfield',
                        height: '',
                        width: '',
                        label: 'Idioma',
                        labelAlign: 'bottom',
                        labelWidth: '40%',
                        name: 'Language',
                        displayField: 'label',
                        store: 'languageStoreId',
                        valueField: 'idLang\n'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onConfigPanelActivate',
                event: 'activate',
                delegate: '#ConfigPanel'
            }
        ]
    },

    onConfigPanelActivate: function(container, newActiveItem, oldActiveItem, options) {
        
    }

});