/*
 * File: app/view/ui/ConfigPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.view.ui.ConfigPanel', {
    extend: 'Ext.form.Panel',

    config: {
        id: 'ConfigPanel',
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Painometer',
                items: [
                    {
                        xtype: 'button',
                        id: 'okConfig',
                        ui: 'confirm',
                        text: 'OK'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                defaults: {
                    required: true,
                    labelAlign: 'left',
                    labelWidth: '40%'
                },
                layout: {
                    type: 'hbox'
                },
                instructions: 'Opcions generals de l\'eina.',
                title: 'Opcions Generals',
                items: [
                    {
                        xtype: 'selectfield',
                        label: 'Escala',
                        name: 'escalaType',
                        displayField: 'label',
                        store: 'scaleTypesStoreId',
                        valueField: 'idScale'
                    }
                ]
            }
        ]
    }

});