/*
 * File: app/view/ui/FPSRPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PainScales.view.ui.FPSRPanel', {
    extend: 'Ext.form.Panel',

    config: {
        id: 'FPSRPanel',
        layout: {
            type: 'fit'
        },
        scrollable: false,
        items: [
            {
                xtype: 'container',
                docked: 'top',
                id: 'FPSNavContainer',
                padding: 10,
                defaults: {
                    width: 50,
                    height: 60,
                    padding: 10
                },
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'image',
                        id: 'smallFace1',
                        src: 'resources/images/fpsr/small_face1.png'
                    },
                    {
                        xtype: 'image',
                        id: 'smallFace2',
                        src: 'resources/images/fpsr/small_face2.png'
                    },
                    {
                        xtype: 'image',
                        id: 'smallFace3',
                        src: 'resources/images/fpsr/small_face3.png'
                    },
                    {
                        xtype: 'image',
                        id: 'smallFace4',
                        src: 'resources/images/fpsr/small_face4.png'
                    },
                    {
                        xtype: 'image',
                        id: 'smallFace5',
                        src: 'resources/images/fpsr/small_face5.png'
                    },
                    {
                        xtype: 'image',
                        id: 'smallFace6',
                        src: 'resources/images/fpsr/small_face6.png'
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'InfoCaroCont',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'container',
                        docked: 'right',
                        id: 'infoContainer',
                        layout: {
                            align: 'end',
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                id: 'infoBtn',
                                style: 'border:0',
                                ui: 'info_btn-small',
                                width: 22,
                                iconCls: 'info',
                                iconMask: true
                            }
                        ]
                    },
                    {
                        xtype: 'carousel',
                        id: 'FPSCarousel',
                        defaults: {
                            layout: {
                                align: 'start',
                                pack: 'center',
                                type: 'hbox'
                            },
                            defaults: {
                                height: 360,
                                width: 290
                            }
                        },
                        items: [
                            {
                                xtype: 'container',
                                id: 'facesContainer1',
                                itemId: '',
                                value: 0,
                                items: [
                                    {
                                        xtype: 'image',
                                        id: 'face1',
                                        src: 'resources/images/fpsr/cara1.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                id: 'facesContainer2',
                                value: 2,
                                items: [
                                    {
                                        xtype: 'image',
                                        id: 'face2',
                                        src: 'resources/images/fpsr/cara2.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                id: 'facesContainer3',
                                value: 4,
                                items: [
                                    {
                                        xtype: 'image',
                                        id: 'face3',
                                        src: 'resources/images/fpsr/cara3.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                id: 'facesContainer4',
                                value: 6,
                                items: [
                                    {
                                        xtype: 'image',
                                        id: 'face4',
                                        src: 'resources/images/fpsr/cara4.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                id: 'facesContainer5',
                                value: 8,
                                items: [
                                    {
                                        xtype: 'image',
                                        id: 'face5',
                                        src: 'resources/images/fpsr/cara5.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                id: 'facesContainer6',
                                value: 10,
                                items: [
                                    {
                                        xtype: 'image',
                                        id: 'face6',
                                        src: 'resources/images/fpsr/cara6.png'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});