/*
 * File: app/view/ui/VASPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.view.ui.VASPanel', {
    extend: 'Ext.Container',

    config: {
        html: 'VASPanel under construction',
        style: 'background-color:white;',
        ui: '',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'container',
                cls: [
                    'sencha-vas-slider'
                ],
                id: 'VASSliderContainer',
                style: 'background-color:white;',
                items: [
                    {
                        xtype: 'sliderfield',
                        centered: true
                    }
                ]
            },
            {
                xtype: 'container',
                docked: 'right',
                id: 'infoContainer',
                layout: {
                    align: 'end',
                    pack: 'end',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'infoBtn',
                        style: 'border:0',
                        ui: 'info_btn-small',
                        width: 22,
                        iconCls: 'info',
                        iconMask: true
                    }
                ]
            }
        ]
    }

});