/*
 * File: designer.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Config',
        'ScaleTypes',
        'Language'
    ],

    stores: [
        'scaleTypesStore',
        'languageStore'
    ],

    views: [
        'MainContainer',
        'NRS11Panel',
        'CASPanel',
        'ConfigPanel',
        'FPSRPanel',
        'InfoContainer',
        'CreditsContainer',
        'VASPanel'
    ],

    glossOnIcon: true,

    name: 'Painometer',

    controllers: [
        'ConfigController',
        'FPSRPanel',
        'NRS11Panel',
        'CreditsContainer'
    ],

    launch: function() {
        Ext.create('Painometer.view.MainContainer', {fullscreen: true});
    }
});
