/*
 * File: designer.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Config',
        'ScaleType',
        'LanguageType'
    ],

    stores: [
        'ScaleTypes',
        'LanguageTypes'
    ],

    views: [
        'MainContainer',
        'NRS11Panel',
        'CASPanel',
        'ConfigPanel',
        'FPSRPanel',
        'InfoContainer',
        'CreditsContainer',
        'VASPanel',
        'ConfigCard',
        'OrientationInfo'
    ],

    glossOnIcon: true,

    name: 'Painometer',

    controllers: [
        'ConfigController',
        'FPSRPanel',
        'NRS11Panel',
        'CreditsContainer',
        'CASPanelController',
        'VASPanel',
        'OrientationController'
    ],

	// data mars of the application
	painometerData : null, // instance of the current state
	
	getPainometerData: function() {
		if (this.painometerData === null) {
			this.painometerData = Ext.create('Painometer.model.Config', {id : 1});
		}
		return this.painometerData;
	},
	
    launch: function() {
    	this.loadData();
    },
    
    
    /* the data */
    loadData: function() {
    	var configModel = Ext.ModelMgr.getModel('Painometer.model.Config');
        configModel.load(1, {
            scope: this,
            failure: function(record) {
                this.getPainometerData().save();
            }, 
            success: function (record) {
            	this.painometerData = record;
            },
            callback: function() {
            	var configController = this.getController("ConfigController");
            	Ext.create('Painometer.view.MainContainer', {fullscreen: true});
        		this.showView();
            }
        });
    },
    
    getValue: function() {
        return this.getPainometerData().get('value');
    },

    setValue: function(newValue) {
        this.getPainometerData().set('value', newValue);
        this.getPainometerData().save();
    },
    
    getValue: function() {
        return this.getApplication().getPainometerData().get('value');
    },
    
    setScale: function(newScale) {
        this.getPainometerData().set('scale', newScale);
        this.getPainometerData().save();
    },
    
    getScale: function() {
        return this.getApplication().getPainometerData().get('scale');
    },
    
    setReset: function(newValue) {
    	this.getPainometerData().set('reset', newValue);
    	this.getPainometerData().save();
    },
    
    isReset: function() {
    	return this.getApplication().getPainometerData().get('reset');
    },
    
    setViewIndex: function(newViewIndex) {
    	this.getPainometerData().set('viewIndex', newViewIndex);
    	this.getPainometerData().save();
    },
    
    getViewIndex: function() {
    	return this.getPainometerData().get('viewIndex');
    },
    
    showView: function() {
    	var main = Ext.Viewport.getItems().get("MainContainer");
    	main.setActiveItem(this.getPainometerData().get('viewIndex'));
    },
    
});
