/*
 * File: app/store/base/painStore.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.store.base.painStore', {
    extend: 'Ext.data.Store',
    requires: [
        'Painometer.model.Pain'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                valor: 1,
                language: 1,
                scale: 1
            }
        ],
        model: 'Painometer.model.Pain',
        storeId: 'painStoreId',
        proxy: {
            type: 'localstorage'
        },
        listeners: [
            {
                fn: 'onStoreLoad',
                event: 'load'
            }
        ]
    }
});