/*
 * File: app/controller/AppMainController.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.controller.AppMainController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainContainer: '#MainContainer'
        },

        control: {
            "MainContainer": {
                move: 'MainContainerMove'
            }
        }
    },

    init: function() {

        Ext.Viewport.on({
            scope: this,
            orientationchange: function(viewport, newOrientation, width, height) {
                vw = viewport; no = newOrientation; wi = width; he = height;
                alert("ei!!!!");
            }
        });
    },

    MainContainerMove: function(container, item, toIndex, fromIndex, options) {

    },

    isLandscape: function() {
        Ext.Viewport.on({
            scope: this,
            orientationchange: function(viewport, newOrientation, width, height) {
                vw = viewport; no = newOrientation; wi = width; he = height;
                alert("ei!!!!");
                if (no == portrait){
                    return "false"; 
                }
                else{
                    return "true";
                }
            }
        });

    },

    isPortrait: function() {
        Ext.Viewport.on({
            scope: this,
            orientationchange: function(viewport, newOrientation, width, height) {
                vw = viewport; no = newOrientation; wi = width; he = height;
                alert("ei!!!!");
                if (no == landscape){
                    return "true"; 
                }
                else{
                    return "false";
                }
            }
        });
    }

});