/*
 * File: app/controller/AppMainController.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.controller.AppMainController', {
    extend: 'Ext.app.Controller',

    config: {
        orientation: true,
        refs: {
            scaleSel: '#ScaleSel',
            OverlayCAS: '#OverlayCAS',
            OverlayVAS: '#OverlayVAS',
            OverlayFPS: '#OverlayFPS',
            OverlayFPS2: '#OverlayFPS2'
        }
    },

    init: function() {
        Ext.Viewport.on({
            scope: this,
            orientationchange: function(viewport, newOrientation, width, height) {
                var overlaycas = this.getOverlayCAS();
                var overlayvas = this.getOverlayVAS();
                var overlayfps = this.getOverlayFPS();
                var overlayfps2 = this.getOverlayFPS2();
                var scalesel = this.getScaleSel().getValue();

                if((newOrientation == "portrait")&&(scalesel == 2)){
                    overlaycas.setHidden(false);
                }
                if((newOrientation == "landscape")&&(scalesel == 2)){
                    overlaycas.setHidden(true);
                }
                if((newOrientation == "portrait")&&(scalesel == 3)){
                    overlayvas.setHidden(false);
                }
                if((newOrientation == "landscape")&&(scalesel == 3)){
                    overlayvas.setHidden(true);
                }
                if((newOrientation == "portrait")&&(scalesel === 0)){
                    overlayfps.setHidden(true);
                    overlayfps2.setHidden(true);
                }
                if((newOrientation == "landscape")&&(scalesel === 0)){
                    overlayfps.setHidden(false);
                    overlayfps2.setHidden(false);
                }
                this.setOrientation(newOrientation == "landscape");
            }
        });
    },

    isLandscape: function() {
        return this.getOrientation();

    },

    isPortrait: function() {
        return !this.getOrientation();
    }

});