/*
 * File: app/controller/AppMainController.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.controller.AppMainController', {
    extend: 'Ext.app.Controller',

    config: {
        orientation: true,
        refs: {
            scaleSel: '#ScaleSel',
            OverlayCAS: '#OverlayCAS',
            OverlayVAS: '#OverlayVAS'
        }
    },

    init: function() {
        Ext.Viewport.on({
            scope: this,
            orientationchange: function(viewport, newOrientation, width, height) {
                if((newOrientation == "portrait")&&(this.getScaleSel().getValue() == 2)){
                    this.getOverlayCAS().setHidden(false);
                }
                if((newOrientation == "landscape")&&(this.getScaleSel().getValue() == 2)){
                    this.getOverlayCAS().setHidden(true);
                }
                if((newOrientation == "portrait")&&(this.getScaleSel().getValue() == 3)){
                    this.getOverlayVAS().setHidden(false);
                }
                if((newOrientation == "landscape")&&(this.getScaleSel().getValue() == 3)){
                    this.getOverlayVAS().setHidden(true);
                }
                this.setOrientation(newOrientation == "landscape");
            }
        });
    },

    isLandscape: function() {
        return this.getOrientation();

    },

    isPortrait: function() {
        return !this.getOrientation();
    }

});