/*
 * File: app/controller/ConfigController.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Painometer.controller.ConfigController', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'Config'
        ],
        stores: [
            'ConfigStore'
        ],
        views: [
            'ConfigPanel'
        ],
        refs: {
            okConfig: '#okConfig',
            ValueCont: '#ValueCont',
            mainContainer: '#MainContainer',
            scaleSel: '#ScaleSel',
            infoBtn: '#infoBtn',
            creditsbtn: '#creditsbtn',
            configCard: '#ConfigCard'
        },

        control: {
            "okConfig": {
                tap: 'onConfigTap'
            },
            "infoBtn": {
                tap: 'onButtonTap'
            },
            "ConfigStore": {
                load: 'onStoreLoad'
            },
            "creditsbtn": {
                tap: 'creditsbtnTap'
            },
            "configpanel": {
                activate: 'onConfigPanelActivate'
            }
        }
    },

    init: function() {
        var configDefault = Ext.create('Painometer.model.Config', {
            scale    : 0,
            language : 0,
            value    : 0
        });

        this.configInstance = configDefault;

        this.configStore = Ext.getStore("configStoreId");
        this.configStore.on('load', this.onStoreLoad, this);
        this.configStore.load();

    },

    onConfigTap: function(button, e, options) {
        var me = this;
        var scale = me.getScaleSel().getValue();
        me.getMainContainer().setActiveItem(scale);
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {
        if (Ext.isEmpty(records)) {
            // no hi ha cap registre
            //alert("onstoreload is empty");
            store.add(this.configInstance);
            store.sync();
        } 

        this.configInstance = store.first();
    },

    setValue: function(newValue) {
        this.configInstance.set('value', newValue);
        //
        //this.getValueCont().setData({'value' : newValue});
        cc = this;
    },

    onButtonTap: function(button, e, options) {
        var me = this;
        me.configStore.sync();
        me.getMainContainer().setActiveItem(4);
    },

    creditsbtnTap: function(button, e, options) {
        var me = this;
        var card = me.getConfigCard();
        var layout = card.getLayout();
        var inn = layout.getAnimation().getInAnimation();
        var out = layout.getAnimation().getOutAnimation();

        inn.setDirection("left");
        out.setDirection("left");
        card.setActiveItem(1);
    },

    onConfigPanelActivate: function(container, newActiveItem, oldActiveItem, options) {
        var newValue = this.configInstance.get('value');

        this.getValueCont().setData({'value' : newValue});
    }

});