/*
 * File: app/controller/CreditsContainer.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.controller.CreditsContainer', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            config: '#config',
            configCard: '#ConfigCard'
        },

        control: {
            "config": {
                tap: 'configTap'
            }
        }
    },

    configTap: function(button, e, options) {
        var me = this;
        var card = me.getConfigCard();
        var layout = card.getLayout();
        var inn = layout.getAnimation().getInAnimation();
        var out = layout.getAnimation().getOutAnimation();

        inn.setDirection("right");
        out.setDirection("right");
        card.setActiveItem(0);
    }

});