/*
 * File: app/controller/FPSRPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('PainScales.controller.FPSRPanel', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            faceContainer: '#FPSCarousel container',
            fpsNav: '#FPSNavContainer'
        },

        control: {
            "faceContainer": {
                activate: 'faceActivate'
            }
        }
    },

    faceActivate: function(container, newActiveItem, oldActiveItem, options) {

        if (!Ext.isEmpty(container) && !Ext.isEmpty(oldActiveItem)) {
            var newIndex = container.config.value / 2;
            var oldIndex = oldActiveItem.config.value / 2;

            var newFace    = this.getFpsNav().items.getAt(newIndex);
            var oldFace = this.getFpsNav().items.getAt(oldIndex);

            oldFace.removeCls("face-selected");
            newFace.addCls("face-selected");
        }

    }

});