/*
 * File: app/controller/NRS11Panel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Painometer.controller.NRS11Panel', {
    extend: 'Ext.app.Controller',

    config: {
        stores: [
            'ConfigStore'
        ],
        views: [
            'NRS11Panel'
        ],
        refs: {
            numContainer: '#NRSCarousel container',
            nrsNav: '#NRSNavContainer',
            infoBtn2: '#infoBtn2',
            mainContainer: '#MainContainer',
            NRS11Panel: '#Nrs11Panel',
            NRSCarousel: '#NRSCarousel'
        },

        control: {
            "numContainer": {
                activate: 'numActivate'
            },
            "infoBtn2": {
                tap: 'onInfoButtonTap'
            },
            "NRS11Panel": {
                activate: 'onNRS11PanelActivate'
            }
        }
    },

    numActivate: function(container, newActiveItem, oldActiveItem, options) {


        if (!Ext.isEmpty(oldActiveItem)) {
            var oldIndex = oldActiveItem.config.value;
            var oldFace = this.getNrsNav().items.getAt(oldIndex);

            oldFace.removeCls("face-selected");
        }

        if (!Ext.isEmpty(container)) {
            var newIndex = container.config.value;
            var newFace    = this.getNrsNav().items.getAt(newIndex);

            newFace.addCls("face-selected");
        }

        /* guardar valor al model */
        /* guardar model al disc */;
    },

    onInfoButtonTap: function(button, e, options) {


        var me = this;
        me.getMainContainer().setActiveItem(4);
    },

    onNRS11PanelActivate: function(container, newActiveItem, oldActiveItem, options) {

        var storeConfig = Ext.getStore("configStoreId");
        var dataStore   = storeConfig.getData();
        var configModel = dataStore.getAt(0);

        var value = configModel.get("value");

        var pan = this.getNRSCarousel();

        pan.setActiveItem(value);
    }

});