/*
 * File: app/controller/VASPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Painometer.controller.VASPanel', {
    extend: 'Ext.app.Controller',

    config: {
        models: ['Config'],
        views: ['VASPanel'],
        refs: {
            VASSlider: '#VASSlider',
            OverlayVAS: '#OverlayVAS'
        },

        control: {
        	"VASSlider": {change: 'onVASSliderChange'},
            "VASPanel" : {activate: 'onVASPanelActivate'}
        },
        // user variables
        configController  : null,
    },
    
	init: function() {
    	var app = this.getApplication();
    	this.setConfigController(app.getController("Painometer.controller.ConfigController"));
	}, 
	
    onVASSliderChange: function(slider, thumb, newValue, oldValue, options) {
        this.getConfigController().setValue(newValue);
    },

    onVASPanelActivate: function(container, newActiveItem, oldActiveItem, options) {
        var value  = this.getConfigController().getValue();
        var slider = this.getVASSlider();
        slider.setValue(value);
    }

});